In [24]:
import requests
from bs4 import BeautifulSoup
import openpyxl
import pandas as pd

In [7]:
job=[]

In [26]:
for i in range(1,11):
    url=f'https://www.timesjobs.com/candidate/job-search.html?from=submit&luceneResultSize=25&txtKeywords=0DQT0data%20analyst0DQT0&postWeek=60&searchType=personalizedSearch&actualTxtKeywords=Data%20Analyst&searchBy=0&rdoOperator=OR&pDate=I&sequence={i}&startPage=1'
    source=requests.get(url)
    soup=BeautifulSoup(source.text,'lxml')
    tags=soup.find_all('li',class_="clearfix job-bx wht-shd-bx")
    
    for tag in tags:
        company_name=tag.find('h3',class_="joblist-comp-name").text.rstrip().lstrip().replace('(More Jobs)','')
        skills=tag.find('span',class_="srp-skills").text.rstrip().lstrip()
        exp=tag.find('ul',class_="top-jd-dtl clearfix").text[12:21]
        loc=tag.span.text.replace('(More Jobs)','')
        link=tag.h2.a['href']
        print(company_name,skills,exp,loc,link)
        job.append([company_name,skills,exp,loc,link])
        sheet.append([company_name,skills,exp,loc,link])

Information Services Group data analysis  ,   python  ,   excel  ,   sql  ,   communication skills   ,  bi  ,  data extraction  ,  database  ,  git  ,  technical skills  ,  machine learning  ,  infrastructure  ,  data communication 2 - 3 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-associate-data-analyst-data-analyst-information-services-group-bengaluru-bangalore-2-to-3-yrs-jobid-tFjUvgIXFkdzpSvf__PLUS__uAgZw==&source=srp
Zoxima Solutions Pvt. Ltd. reports  ,  Data Analysts  ,  MySQL 3 - 8 yrs  https://www.timesjobs.com/job-detail/data-analysts-zoxima-solutions-pvt-ltd-3-to-8-yrs-jobid-ykoXKM9SnchzpSvf__PLUS__uAgZw==&source=srp
RDA Labs bi  ,  dashboards  ,  data analyst  ,  impact analysis  ,  analyst 1 - 3 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-rda-labs-bengaluru-bangalore-1-to-3-yrs-jobid-IC1XfaBmtthzpSvf__PLUS__uAgZw==&source=srp
Best Infosystems Ltd.
      DATA ANALYST  ,  SAP ABAP  ,  HTML5 and CSS 6 - 10 yr   https://www.timesjobs.com/job-detail/data-analyst-best-infosystems-ltd-gurgaon-6-to-10-yrs-jobid-CkO__SLASH__yK8kjhNzpSvf__PLUS__uAgZw==&source=srp
the modern dimension oracle  ,  sas  ,  bi  ,  dashboards  ,  data analyst  ,  alteryx  ,  sql  ,  tableau 3 - 6 yrs Delhi,  Delhi/NCR,  Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-the-modern-dimension-delhi-delhi-ncr-bengaluru-bangalore-3-to-6-yrs-jobid-MLY5JvW__PLUS__ks9zpSvf__PLUS__uAgZw==&source=srp
ADROIT LEARNING AND MANPOWER PVT LTD data analysis  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  infrastructure  ,  data visualization 7 - 10 yr Ahmedabad https://www.timesjobs.com/job-detail/data-analyst-adroit-learning-and-manpower-pvt-ltd-ahmedabad-7-to-10-yrs-jobid-O6rsbebTEJNzpSvf__PLUS__uAgZw==&source=srp
HyreFox Consultants data analytics  ,  business requirements  ,  bi  ,  dashboards  ,  data analyst  ,  sql  ,  tableau 0 - 3 yrs Jaipur https://www.timesjobs.com/job-detail/data-analyst-hyrefox-consultants-jaipur-0-to-3-yrs-jobid-xI2bjtkBOw5zpSvf__PLUS__uAgZw==&source=srp
Uscreen dashboards  ,  sql  ,  data visualization  ,  data analytics  ,  data analysis  ,  customer success  ,  mobile  ,  data analyst 3 - 6 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-uscreen-bengaluru-bangalore-3-to-6-yrs-jobid-kL__PLUS__HWMsY8p5zpSvf__PLUS__uAgZw==&source=srp
cibirix digital media advanced analytics  ,  visualization  ,  data analytics  ,  bi  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  data visualization 2 - 5 yrs  https://www.timesjobs.com/job-detail/data-analyst-cibirix-digital-media-2-to-5-yrs-jobid-gHpu48XKd2hzpSvf__PLUS__uAgZw==&source=srp
Brainvire Infotech data analysis   ,   excel proficiency   ,   report generation   ,   data visualization   ,   good communication   ,  dashboards  ,  data analyst  ,  data extraction 0 - 1 yrs Mumbai https://www.timesjobs.com/job-detail/data-analyst-brainvire-infotech-mumbai-0-to-1-yrs-jobid-UtVt9QayLwVzpSvf__PLUS__uAgZw==&source=srp
Principal Financial Services Inc. visualization  ,  bi  ,  sql  ,  data science  ,  statistical modeling  ,  oracle  ,  data analytics  ,  sas  ,  consulting  ,  data analyst  ,  alteryx  ,  tableau 0 - 2 yrs Pune https://www.timesjobs.com/job-detail/data-analyst-principal-financial-services-inc-pune-0-to-2-yrs-jobid-VKvYRf3dn9xzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-rohtak-shimla-solan-jammu-srinagar-1-to-6-yrs-jobid-XipJBvZWODFzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-visakhapatnam-guwahati-patna-raipur-panjim-panaji-1-to-6-yrs-jobid-IZwJQA6o2aZzpSvf__PLUS__uAgZw==&source=srp
Edifecs release planning   ,   business requirements   ,   agile   ,   scrum   ,   risk evaluation   ,  business analysis  ,  product analyst 3 - 6 yrs Mohali https://www.timesjobs.com/job-detail/data-analyst-edifecs-mohali-3-to-6-yrs-jobid-y9SIVIewpuNzpSvf__PLUS__uAgZw==&source=srp
Edifecs release planning   ,   business requirements   ,   agile   ,   scrum   ,   risk evaluation   ,  business analysis  ,  product analyst 3 - 6 yrs Mohali https://www.timesjobs.com/job-detail/data-analyst-edifecs-mohali-3-to-6-yrs-jobid-DL7__SLASH__0YKfwrdzpSvf__PLUS__uAgZw==&source=srp
Ipseity Group reports  ,  vb  ,  data collection  ,  xml  ,  procedures 1 - 3 yrs Bhopal https://www.timesjobs.com/job-detail/data-analyst-ipseity-group-bhopal-1-to-3-yrs-jobid-ADc3ie9lzZBzpSvf__PLUS__uAgZw==&source=srp
advanced risk analytics private limited visualizing data  ,  data collection  ,  Flood data 0 - 3 yrs Pune https://www.timesjobs.com/job-detail/data-analyst-advanced-risk-analytics-private-limited-pune-0-to-3-yrs-jobid-TmPblskT8fVzpSvf__PLUS__uAgZw==&source=srp
myglamm popxo data analysis   ,   excel   ,   sql   ,   python   ,   communication skills   ,  bi  ,  dashboards  ,  data visualization  ,  tableau  ,  analyst 2 - 4 yrs Delhi/NCR https://www.timesjobs.com/job-detail/data-analyst-myglamm-popxo-delhi-ncr-2-to-4-yrs-jobid-6pvL3yYCARNzpSvf__PLUS__uAgZw==&source=srp
Travel Centric Technology information technology  ,  team player  ,  sql 2 - 5 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-travel-centric-technology-bengaluru-bangalore-2-to-5-yrs-jobid-CvE6i__SLASH__GBMh5zpSvf__PLUS__uAgZw==&source=srp
Hexanika test data  ,  sql queries  ,  testing  ,  sql 0 - 3 yrs Pune https://www.timesjobs.com/job-detail/data-analyst-hexanika-pune-0-to-3-yrs-jobid-uV1krqn6UrlzpSvf__PLUS__uAgZw==&source=srp
BUSISOL SOURCING INDIA PVT. LTD charts  ,  data mining  ,  formulas  ,  relational database  ,  sql server  ,  reporting services 0 - 3 yrs Mumbai https://www.timesjobs.com/job-detail/data-analyst-busisol-sourcing-india-pvt-ltd-mumbai-0-to-3-yrs-jobid-ARJVvDp1IFtzpSvf__PLUS__uAgZw==&source=srp
zf india pvt ltd data analysis   ,   erp systems   ,   ms powerbi   ,   sql   ,   statistical analysis   ,  vehicles  ,  engineering environment  ,  motion control  ,  safety  ,  manufacturing  ,  action  ,  driveline  ,  maintenance 3 - 6 yrs Coimbatore https://www.timesjobs.com/job-detail/data-analyst-zf-india-pvt-ltd-coimbatore-3-to-6-yrs-jobid-Yk4YT__PLUS__t6NuJzpSvf__PLUS__uAgZw==&source=srp
BUSISOL SOURCING INDIA PVT. LTD reports  ,  charts  ,  data mining  ,  formulas  ,  reporting services  ,  relational database  ,  sql server 0 - 3 yrs Delhi https://www.timesjobs.com/job-detail/data-analyst-busisol-sourcing-india-pvt-ltd-delhi-0-to-3-yrs-jobid-8prYmLkFDLdzpSvf__PLUS__uAgZw==&source=srp
mobileforce website  ,  campaigns  ,  google analytics  ,  social media 0 - 3 yrs Indonesia https://www.timesjobs.com/job-detail/data-analyst-mobileforce-indonesia-0-to-3-yrs-jobid-ui__PLUS__OIaW1O0VzpSvf__PLUS__uAgZw==&source=srp
ANZ GRINDLAYS BANK hr data knowledge  ,   business acumen  ,   advanced excel  ,   powerpoint   (  intermediate  /  advanced  )    ,   data visualization and dashboarding   ,  bi  ,  sql  ,  python  ,  servicenow 8 - 11 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-anz-grindlays-bank-bengaluru-bangalore-8-to-11-yrs-jobid-UGWCv4a4UfpzpSvf__PLUS__uAgZw==&source=srp
HyreFox Consultants excel  ,  reports  ,  reporting  ,  monthly reports 0 - 3 yrs Jaipur https://www.timesjobs.com/job-detail/data-analyst-hyrefox-consultants-jaipur-0-to-3-yrs-jobid-KwT1r6nTXxFzpSvf__PLUS__uAgZw==&source=srp
Nineleaps data mining  ,  bi  ,  sql  ,  xml  ,  python  ,  javascript 7 - 10 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-nineleaps-bengaluru-bangalore-7-to-10-yrs-jobid-wcuAhY0JpsFzpSvf__PLUS__uAgZw==&source=srp
YuktaMedia LLP Information Systems  ,   Computer Science  ,   Computer Engineering  ,  Software Engineering 0 - 2 yrs Pune https://www.timesjobs.com/job-detail/data-analyst-yuktamedia-llp-pune-0-to-2-yrs-jobid-PZwH4yGnIwBzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   hypothesis  ,   reports  ,   data science  ,   business analytics   ,  director 5 - 9 yrs Mumbai https://www.timesjobs.com/job-detail/data-analyst-anicalls-pty-ltd-mumbai-5-to-9-yrs-jobid-2SVQQW4Tv3VzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   hypothesis  ,   reports  ,   data science  ,   business analytics   ,  director 5 - 9 yrs Mumbai https://www.timesjobs.com/job-detail/data-analyst-anicalls-pty-ltd-mumbai-5-to-9-yrs-jobid-4EM0d6__PLUS__H7d9zpSvf__PLUS__uAgZw==&source=srp
TE Connectivity Ltd sql   ,   etl   ,   data modelling   ,   tableau dashboard   ,   python   ,  computer programming  ,  salesforce  ,  java  ,  big data  ,  visual studio  ,  sharepoint  ,  database management  ,  crm  ,  ruby 2 - 4 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-te-connectivity-ltd-bengaluru-bangalore-2-to-4-yrs-jobid-URBUO8w2z5lzpSvf__PLUS__uAgZw==&source=srp
Clarivate Analytics data analysis   ,   data mining   ,   sql   ,   advanced excel   ,   us healthcare   ,  compensation 1 - 4 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-clarivate-analytics-bengaluru-bangalore-1-to-4-yrs-jobid-8__SLASH__mM__SLASH__6TV0epzpSvf__PLUS__uAgZw==&source=srp
ivy tech solutions data quality  ,  information technology  ,  etl  ,  data integration 0 - 3 yrs  https://www.timesjobs.com/job-detail/data-analyst-ivy-tech-solutions-0-to-3-yrs-jobid-GTWuhWzZHmpzpSvf__PLUS__uAgZw==&source=srp
vixplor analytics pvt ltd Marketing Ability  ,   Leadership Qualities  ,   Communication Skill  ,   Achieving Sales Target  ,   Fluent in Hindi   ,  marketing  ,  sales 0 - 5 yrs Kolkata https://www.timesjobs.com/job-detail/data-analyst-vixplor-analytics-pvt-ltd-kolkata-0-to-5-yrs-jobid-CksdzzcZwZZzpSvf__PLUS__uAgZw==&source=srp
kudosindia test cases  ,  database  ,  metrics  ,  component testing 0 - 3 yrs Mumbai https://www.timesjobs.com/job-detail/data-analysts-kudosindia-mumbai-0-to-3-yrs-jobid-v48SsInbeSRzpSvf__PLUS__uAgZw==&source=srp
alliance recruitment agency python  ,  sql  ,   Python Strong 8 - 10 yr Anand https://www.timesjobs.com/job-detail/data-analyst-alliance-recruitment-agency-anand-8-to-10-yrs-jobid-Vu0zuigTsTlzpSvf__PLUS__uAgZw==&source=srp
alliance recruitment agency python  ,  problem solving  ,  sql 8 - 10 yr Ahmedabad https://www.timesjobs.com/job-detail/data-analyst-alliance-recruitment-agency-ahmedabad-8-to-10-yrs-jobid-VdCPOPjDsSZzpSvf__PLUS__uAgZw==&source=srp
TandA HR Solutions sas  ,  data mining  ,  javascript  ,  sql  ,  business objects  ,  xml 2 - 5 yrs Mohali https://www.timesjobs.com/job-detail/data-analyst-tanda-hr-solutions-mohali-2-to-5-yrs-jobid-DFuI5XIdzyhzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-agra-kanpur-lucknow-dehradun-siliguri-1-to-6-yrs-jobid-bICMUwApQLBzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-coimbatore-madurai-salem-trichy-agartala-1-to-6-yrs-jobid-iu6NEo0UtaZzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-bhubaneshwar-amritsar-jalandhar-ludhiana-jaipur-1-to-6-yrs-jobid-KusMpi0WKF9zpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-indore-aurangabad-nagpur-nasik-thane-1-to-6-yrs-jobid-L1xo8h7MEtdzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-calicut-kozhikode-cochin-kochi-ernakulam-thiruvananthapuram-bhopal-gwalior-1-to-6-yrs-jobid-EbJDjiuEj4FzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-surat-vadodara-ranchi-mangalore-mysoru-mysore-1-to-6-yrs-jobid-d5EDId8OuNRzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-ahmedabad-kolkata-pune-chandigarh-navi-mumbai-1-to-6-yrs-jobid-LAofElYdu7tzpSvf__PLUS__uAgZw==&source=srp
Techno wise
      "Data Analytics"  ,  SQL  ,  "MS Excel"  ,  "Reporting Tools"  ,  "Qlikview"  ,  "Tableau"  ,  "Credit Risk"  ,  "BFSI" 4 - 7 yrs   https://www.timesjobs.com/job-detail/data-analyst-techno-wise-ahmedabad-bengaluru-bangalore-chennai-hyderabad-secunderabad-pune-4-to-7-yrs-jobid-Wg9hbWWER5FzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-rohtak-shimla-solan-jammu-srinagar-1-to-6-yrs-jobid-RD7xzfkOuI5zpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-agra-kanpur-lucknow-dehradun-siliguri-1-to-6-yrs-jobid-BgZoINlY__PLUS__dxzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      Data Analysis  ,  data analyst  ,  excel  ,  python  ,  sql  ,  nosql  ,  mongodb  ,  bigquery  ,  apache airflow  ,  eda  ,  etl  ,  pyspark  ,  machine learning  ,  django  ,  git  ,  aws  ,  hive  ,  tableau  ,  business analyst 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-bengaluru-bangalore-chennai-delhi-ncr-hyderabad-secunderabad-mumbai-1-to-6-yrs-jobid-EhiB2gSmUP5zpSvf__PLUS__uAgZw==&source=srp
Information Services Group data analysis   ,   database management   ,   sql   ,   data visualization   ,   statistical analysis    ,  mysql  ,  big data  ,  python  ,  oracle  ,  nosql  ,  cassandra  ,  storage  ,  data extraction  ,  postgresql  ,  hadoop  ,  technical skills  ,  mongodb  ,  cloud services  ,  machine learning  ,  infrastructure 4 - 5 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-senior-data-analyst-information-services-group-bengaluru-bangalore-4-to-5-yrs-jobid-FGJkg3wtvCJzpSvf__PLUS__uAgZw==&source=srp

Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-surat-vadodara-ranchi-mangalore-mysoru-mysore-1-to-6-yrs-jobid-lfoJsCpyD1VzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-guwahati-patna-raipur-panjim-panaji-navi-mumbai-1-to-6-yrs-jobid-RSRsuTdXBYxzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-coimbatore-madurai-salem-trichy-agartala-1-to-6-yrs-jobid-rUEfbdVYEIRzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-bhubaneshwar-amritsar-jalandhar-ludhiana-jaipur-1-to-6-yrs-jobid-IUq9V__SLASH__bdfglzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-indore-aurangabad-nagpur-nasik-thane-1-to-6-yrs-jobid-rfG__PLUS__YOzs__SLASH__CxzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-calicut-kozhikode-cochin-kochi-ernakulam-thiruvananthapuram-bhopal-gwalior-1-to-6-yrs-jobid-__PLUS__tDX__SLASH__P6y5jtzpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-ahmedabad-kolkata-pune-chandigarh-visakhapatnam-1-to-6-yrs-jobid-u__SLASH__GPEIjci35zpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      python  ,  business intelligence  ,  analytics  ,  Data Analytics  ,  data analysis  ,  power bi  ,  pandas  ,  coding  ,  tableau  ,  reporting 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-bengaluru-bangalore-chennai-delhi-ncr-hyderabad-secunderabad-mumbai-1-to-6-yrs-jobid-ZqVd7xDHNH9zpSvf__PLUS__uAgZw==&source=srp
Canvas Facilities
      data analysis  ,  sql  ,  advanced excel  ,  data analyst  ,  analyst  ,  fresher  ,  trainee 1 - 6 yrs   https://www.timesjobs.com/job-detail/data-analyst-canvas-facilities-bengaluru-bangalore-chennai-delhi-ncr-hyderabad-secunderabad-mumbai-1-to-6-yrs-jobid-DOKqkc5h25VzpSvf__PLUS__uAgZw==&source=srp
Prime immigration llp
      software engineer  ,  software developer  ,  senior software engineer  ,  consultant  ,  it analyst  ,  Senior Data Analyst  ,  senior software developer  ,  Business Analysis 2 - 7 yrs   https://www.timesjobs.com/job-detail/data-analyst-senior-data-analyst-senior-analyst-prime-immigration-llp-australia-canada-germany-singapore-null-2-to-7-yrs-jobid-NdazPyzHXdFzpSvf__PLUS__uAgZw==&source=srp
AIN Staffing
      data entry work   ,  funtional area  ,  Ms Office  ,  team leader 1 - 3 yrs   https://www.timesjobs.com/job-detail/data-management-data-analyst-senior-data-analyst-ain-staffing-ahmedabad-bengaluru-bangalore-noida-greater-noida-andaman-nicobar-chandigarh-1-to-3-yrs-jobid-__PLUS__llXUKwUIWNzpSvf__PLUS__uAgZw==&source=srp
IRT Computer Solutions  ( I )  Pvt Ltd tableau  ,  qlik sense  ,  bi  ,  report builder  ,  data analyst 4 - 7 yrs Hyderabad/Secunderabad,  Chennai https://www.timesjobs.com/job-detail/data-analyst-power-bi-irt-computer-solutions-i-pvt-ltd-hyderabad-secunderabad-chennai-4-to-7-yrs-jobid-YNMP9rCUQstzpSvf__PLUS__uAgZw==&source=srp
gantec publishing solutions pvt. ltd. sas  ,  information technology  ,  bi  ,  data analyst  ,  sql  ,  tableau  ,  tableau developer 0 - 3 yrs  https://www.timesjobs.com/job-detail/data-analyst-and-tableau-developer-gantec-publishing-solutions-pvt-ltd-0-to-3-yrs-jobid-2kuA7KvYhnBzpSvf__PLUS__uAgZw==&source=srp
alliance recruitment agency data analysis  ,  data analyst  ,  vba  ,  business consulting  ,  analyst 2 - 8 yrs Switzerland https://www.timesjobs.com/job-detail/data-analyst-python-alliance-recruitment-agency-switzerland-2-to-8-yrs-jobid-EuV7B2l__PLUS__jN9zpSvf__PLUS__uAgZw==&source=srp
Edifecs sql  ,   python  ,   tableau  ,   data visualization  ,   business analysis   ,  business requirements  ,  data analyst 5 - 6 yrs Mohali https://www.timesjobs.com/job-detail/sr-data-analyst-edifecs-mohali-5-to-6-yrs-jobid-dc1Q74RgHjNzpSvf__PLUS__uAgZw==&source=srp
Edifecs sql  ,   python  ,   tableau  ,   data visualization  ,   business analysis   ,  business requirements  ,  data analyst 5 - 6 yrs Mohali https://www.timesjobs.com/job-detail/sr-data-analyst-edifecs-mohali-5-to-6-yrs-jobid-qHnhfuHS__SLASH____PLUS__xzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analyst  ,   reporting  ,   sql server  ,   ssis  ,   ssrs   ,  c# 5 - 8 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/data-analyst-with-jd-edwards-anicalls-pty-ltd-hyderabad-secunderabad-5-to-8-yrs-jobid-BBCbTiNpSv1zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analyst   ,   reports creation   ,   sql server   ,   ssis   ,   ssrs   ,  c# 5 - 8 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-jd-edwards-anicalls-pty-ltd-chennai-5-to-8-yrs-jobid-yAagqdPy9KdzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analyst  ,   reports  ,   sql server  ,   ssis  ,   ssrs   ,  c# 5 - 8 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/data-analyst-jd-edwards-anicalls-pty-ltd-noida-greater-noida-5-to-8-yrs-jobid-MZ7__SLASH__OlhSC9lzpSvf__PLUS__uAgZw==&source=srp
AMAZON INDIA PVT LTD data analytics  ,   automation  ,   capacity planning  ,   business analysis  ,   data mining   ,  business requirements  ,  spss  ,  sql  ,  sas  ,  data analyst 1 - 4 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-ssr-amazon-india-pvt-ltd-bengaluru-bangalore-1-to-4-yrs-jobid-7aAOTqgvhJxzpSvf__PLUS__uAgZw==&source=srp
Gainwell Technologies data analysis   ,   business analysis   ,   medicaid   ,   medicare   ,   claims   ,  business requirements  ,  computer programming  ,  business analyst  ,  data analyst  ,  sql  ,  it projects  ,  business process 4 - 7 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-business-analyst-gainwell-technologies-chennai-4-to-7-yrs-jobid-RCgNPwqAttZzpSvf__PLUS__uAgZw==&source=srp
Gainwell Technologies data analysis   ,   business analysis   ,   medicaid   ,   medicare   ,   claims   ,  business requirements  ,  computer programming  ,  business analyst  ,  data analyst  ,  sql  ,  it projects  ,  business process 4 - 7 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-business-analyst-gainwell-technologies-chennai-4-to-7-yrs-jobid-LLAhQxzxIW1zpSvf__PLUS__uAgZw==&source=srp
zf india pvt ltd supply chain management   ,   project management   ,   data analytics   ,   sap bw   ,   power bi    ,  visualization  ,  data analyst  ,  data visualization 4 - 7 yrs Pune https://www.timesjobs.com/job-detail/supply-chain-data-analyst-zf-india-pvt-ltd-pune-4-to-7-yrs-jobid-7BtYBi3COXBzpSvf__PLUS__uAgZw==&source=srp
Gainwell Technologies data analysis   ,   business analysis   ,   medicaid and medicare   ,   claims   ,   sql   ,  business requirements  ,  computer programming  ,  business analyst  ,  data analyst  ,  it projects  ,  business process 4 - 7 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-ba-gainwell-technologies-chennai-4-to-7-yrs-jobid-n8Ed0FxCTMJzpSvf__PLUS__uAgZw==&source=srp
AMAZON INDIA PVT LTD data analytics   ,   business analysis   ,   statistical techniques   ,   sql   ,   excel   ,  data mining  ,  bi  ,  spss  ,  dashboards  ,  data analysis  ,  sas  ,  data analyst  ,  infrastructure 1 - 2 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/business-data-analyst-glowroad-amazon-india-pvt-ltd-bengaluru-bangalore-1-to-2-yrs-jobid-lY3EFW__PLUS__oHrxzpSvf__PLUS__uAgZw==&source=srp

zf india pvt ltd data analysis   ,   data visualization   ,   erp systems   ,   sql   ,   powerbi   ,  sap bw  ,  data science  ,  data analytics  ,  data analyst  ,  statistical analysis 5 - 8 yrs Coimbatore https://www.timesjobs.com/job-detail/sr-data-analyst-zf-india-pvt-ltd-coimbatore-5-to-8-yrs-jobid-2qH8YQDnrSZzpSvf__PLUS__uAgZw==&source=srp
AMAZON INDIA PVT LTD sql  /  etl  ,   microsoft excel  ,   html  ,   statistical analysis  ,   data visualization   ,  bi  ,  business analyst  ,  dashboards  ,  data scientist  ,  data analysis  ,  data analyst  ,  tableau 3 - 5 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/payroll-data-analyst-payroll-amazon-india-pvt-ltd-hyderabad-secunderabad-3-to-5-yrs-jobid-29ldZFVgL4ZzpSvf__PLUS__uAgZw==&source=srp
Principal Financial Services Inc. visualization  ,  bi  ,  sql  ,  data science  ,  statistical modeling  ,  oracle  ,  data analytics  ,  sas  ,  consulting  ,  data analyst  ,  alteryx  ,  tableau 7 - 8 yrs Pune https://www.timesjobs.com/job-detail/lead-data-analyst-principal-financial-services-inc-pune-7-to-8-yrs-jobid-9wxK4jyL27JzpSvf__PLUS__uAgZw==&source=srp
Infoblox hris data analysis   ,   reporting  &  analytics   ,   data visualization   ,   problem solving   ,   hr technology   ,  dashboards  ,  macros  ,  oracle  ,  data analyst  ,  tableau 2 - 5 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/hris-data-analyst-infoblox-bengaluru-bangalore-2-to-5-yrs-jobid-SeqtiYQJnjJzpSvf__PLUS__uAgZw==&source=srp
Infoblox hris data analysis   ,   reporting  &  analytics   ,   data visualization   ,   problem solving   ,   hr technology   ,  dashboards  ,  macros  ,  oracle  ,  data analyst  ,  tableau 2 - 5 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/hris-data-analyst-infoblox-bengaluru-bangalore-2-to-5-yrs-jobid-wAwxUNrUofZzpSvf__PLUS__uAgZw==&source=srp
Sigmoid data analytics   ,   data visualization   ,   business intelligence   ,   statistical  /  ml techniques   ,   team management   ,  san  ,  advanced analytics  ,  spotfire  ,  bi  ,  data analyst  ,  tableau  ,  data science  ,  client interaction  ,  sql database 3 - 6 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/senior-data-analyst-sigmoid-bengaluru-bangalore-3-to-6-yrs-jobid-HNofGelG6xpzpSvf__PLUS__uAgZw==&source=srp
CTE visualization  ,  information technology  ,  data mining  ,  sql  ,  java  ,  business process improvement  ,  data analytics  ,  data analysis  ,  consulting  ,  business analysis  ,  mining  ,  data analyst  ,  business intelligence reporting  ,  tableau  ,  predictive modeling 7 - 12 yr  https://www.timesjobs.com/job-detail/senior-data-analyst-cte-7-to-12-yrs-jobid-mHffd3opMf9zpSvf__PLUS__uAgZw==&source=srp
TECHNOPARK TRIVANDRUM data analytics  ,   reporting  ,   sql  ,   ms office applications  ,   interpersonal communication   ,  macros  ,  business requirements  ,  excel reporting  ,  bi  ,  ms access  ,  dashboards  ,  data analyst  ,  database  ,  vba 5 - 8 yrs Chennai https://www.timesjobs.com/job-detail/lead-data-analyst-bi-technopark-trivandrum-chennai-5-to-8-yrs-jobid-BtM99G5Y6YxzpSvf__PLUS__uAgZw==&source=srp
Electronic Arts Games  ( India )  Pvt. Ltd. data analysis   ,   business intelligence   ,   data extraction   ,   data cleansing   ,   advanced analytics   ,  dashboards  ,  sql  ,  data science  ,  data analytics  ,  predictive analytics  ,  data analyst  ,  alteryx  ,  tableau 4 - 7 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/senior-data-analyst-electronic-arts-games-india-pvt-ltd-hyderabad-secunderabad-4-to-7-yrs-jobid-FWl5j5TIzPRzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd ms access etl  ,   database data conversion  ,   jde tables  ,   oracle jde file base importing  ,   troubleshooting  ,   data analyst   ,  soa  ,  data mining  ,  sql  ,  xml  ,  sas  ,  information management  ,  javascript  ,  business objects 4 - 6 yrs Chennai https://www.timesjobs.com/job-detail/jd-edward-data-analyst-anicalls-pty-ltd-chennai-4-to-6-yrs-jobid-tqwTjHBeWG1zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd ms access etl  ,   database data conversion  ,   jde tables  ,   oracle jde file base importing  ,   troubleshooting  ,   data analyst   ,  soa  ,  data mining  ,  sql  ,  xml  ,  sas  ,  information management  ,  javascript  ,  business objects 4 - 6 yrs Chennai https://www.timesjobs.com/job-detail/jd-edward-data-analyst-anicalls-pty-ltd-chennai-4-to-6-yrs-jobid-gq__PLUS__hOhd3Q3hzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analyst  ,  engineer  ,  freshers 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-GmvqMhDm6QlzpSvf__PLUS__uAgZw==&source=srp
Alstom Projects India Ltd. data analysis  ,   ui  /  ux knowledge  ,   project management  ,   data visualization  ,   data cleansing   ,  bi  ,  dashboards  ,  database  ,  data science  ,  data analyst  ,  qlik sense  ,  infrastructure 2 - 5 yrs  https://www.timesjobs.com/job-detail/data-analyst-vie-alstom-projects-india-ltd-2-to-5-yrs-jobid-ieXBvNKTDn9zpSvf__PLUS__uAgZw==&source=srp
Alstom Projects India Ltd. data analysis  ,   ui  /  ux knowledge  ,   project management  ,   data visualization  ,   data cleansing   ,  bi  ,  dashboards  ,  database  ,  data science  ,  data analyst  ,  qlik sense  ,  infrastructure 2 - 5 yrs  https://www.timesjobs.com/job-detail/data-analyst-vie-alstom-projects-india-ltd-2-to-5-yrs-jobid-a5S__SLASH__uitRe__SLASH__BzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      developer  ,  data analyst 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-1YPfU__PLUS__kcVFhzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd tableau  ,   excel  ,   sql  ,   python  ,   data analysis   ,  business requirements  ,  business analyst  ,  security  ,  data science  ,  data visualization  ,  data analytics  ,  business environment  ,  data analyst  ,  alteryx  ,  ms office suite 5 - 10 yr Chennai https://www.timesjobs.com/job-detail/senior-business-data-analyst-anicalls-pty-ltd-chennai-5-to-10-yrs-jobid-82NEccDiNOBzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd 1  )   tableau 2  )   excel 3  )   sql 4  )   python 5  )   data visualization   ,  business requirements  ,  business analyst  ,  security  ,  data science  ,  data analytics  ,  business environment  ,  data analyst  ,  alteryx  ,  ms office suite 5 - 10 yr Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/business-data-analyst-anicalls-pty-ltd-hyderabad-secunderabad-5-to-10-yrs-jobid-8HeiKuMVXnRzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analyst  ,  Business Analysis 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-zYK5DtIUskNzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analyst  ,  Business Analysis  ,  jobs 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-KlwUGhHIDMZzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      internship  ,  data analyst  ,  engineer 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-TyrefPkfP8lzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      navi mumbai  ,  data analyst  ,  internship 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-Ul7N__SLASH__E9Yk7lzpSvf__PLUS__uAgZw==&source=srp
SLA Consultants India process analyst  ,  dashboards  ,  ms access  ,  vba  ,  bi  ,  business analyst  ,  sql  ,  advanced excel  ,  data 3 - 5 yrs Noida/Greater Noida,  Gurgaon,  Delhi,  Delhi/NCR https://www.timesjobs.com/job-detail/data-analyst-business-analyst-sla-consultants-india-noida-greater-noida-gurgaon-delhi-delhi-ncr-3-to-5-yrs-jobid-tnz3VmbO75dzpSvf__PLUS__uAgZw==&source=srp
CMOTS INTERNET TECHNOLOGIES PVT LTD MS Excel   ,  VBA   ,    Analysing   ,   Maintaining database   ,   Increasing productivity   ,   Reconciling data   ,   finance   ,  analytical abilities. 0 - 3 yrs Chennai https://www.timesjobs.com/job-detail/financial-data-analysts-cmots-internet-technologies-pvt-ltd-chennai-0-to-3-yrs-jobid-oOF6CDXvKeNzpSvf__PLUS__uAgZw==&source=srp
AIR Worldwide data analysis   ,   data management   ,   sql   ,   data visualization   ,   communication skills   ,  database  ,  api  ,  python  ,  tibco  ,  mining  ,  nosql 2 - 5 yrs Delhi/NCR https://www.timesjobs.com/job-detail/emdm-data-analyst-air-worldwide-delhi-ncr-2-to-5-yrs-jobid-fvc__SLASH__zY6xYn9zpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      core java  ,  software development  ,  data analyst 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-jalgaon-kolhapur-nagpur-solapur-0-to-1-yrs-jobid-ChlQjXq8nXtzpSvf__PLUS__uAgZw==&source=srp

jupiter statistical programming languages   ,   ms excel and powerpoint   ,   tableau or equivalent bi tool   ,   database schema   ,   data analytics   ,  sql  ,  crm  ,  python  ,  problem solving 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/jupiter-data-analyst-ii-jupiter-bengaluru-bangalore-5-to-8-yrs-jobid-ybLde7iWBVdzpSvf__PLUS__uAgZw==&source=srp
PUBLICIS GROUPE hybris  ,  sql  ,  salesforce  ,  episerver  ,  devops  ,  magento  ,  mobile  ,  demandware  ,  drupal  ,  infrastructure 3 - 5 yrs Ahmedabad,  Gurgaon,  Mumbai,  Bengaluru / Bangalore https://www.timesjobs.com/job-detail/senior-data-analyst-publicis-groupe-ahmedabad-gurgaon-mumbai-bengaluru-bangalore-3-to-5-yrs-jobid-eoqJIQtfiahzpSvf__PLUS__uAgZw==&source=srp
Epsilon hive  ,  sql  ,  git  ,  hadoop  ,  python  ,  triggers  ,  messaging 8 - 11 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/lead-data-analyst-epsilon-bengaluru-bangalore-8-to-11-yrs-jobid-4aK5fol84BtzpSvf__PLUS__uAgZw==&source=srp
Girikon bi  ,  data warehousing  ,  sql  ,  salesforce  ,  python  ,  oracle  ,  triggers  ,  consultant  ,  sql database 4 - 7 yrs  https://www.timesjobs.com/job-detail/data-analyst-engineer-girikon-4-to-7-yrs-jobid-__PLUS__tcXBtleSGpzpSvf__PLUS__uAgZw==&source=srp
NIPPON DATA SYSTEM oracle  ,  bi  ,  siebel  ,  sql  ,  oracle erp  ,  mvc  ,  crm 3 - 5 yrs Delhi,  Delhi/NCR https://www.timesjobs.com/job-detail/mis-executive-data-analyst-nippon-data-system-delhi-delhi-ncr-3-to-5-yrs-jobid-Hbp8BAo__SLASH__VDBzpSvf__PLUS__uAgZw==&source=srp
ZeroFOX financial analysis  ,  reports  ,  variance analysis  ,  accounting  ,  closing  ,  cash flow  ,  forecasting  ,  collection  ,  budgeting  ,  finance  ,  internet  ,  expenses 3 - 6 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-finance-zerofox-bengaluru-bangalore-3-to-6-yrs-jobid-rQ4YrRn5cn5zpSvf__PLUS__uAgZw==&source=srp
Zobello.com data mining  ,  data analysis  ,  data modeling 1 - 2 yrs Delhi,  Delhi/NCR https://www.timesjobs.com/job-detail/data-analyst-associate-zobello-com-delhi-delhi-ncr-1-to-2-yrs-jobid-l__SLASH__xvd0V__PLUS__axtzpSvf__PLUS__uAgZw==&source=srp
2SOFT SOLUTIONS PVT LTD bi  ,  data warehousing  ,  sql  ,  database development  ,  database  ,  ssrs  ,  mysql  ,  cloud computing  ,  solution architect  ,  sas  ,  triggers 5 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/sr-data-analyst-2soft-solutions-pvt-ltd-mumbai-5-to-8-yrs-jobid-GXHsvQnYPwdzpSvf__PLUS__uAgZw==&source=srp
green-tree advisory oracle  ,  information management  ,  sas  ,  data mining  ,  ms access  ,  javascript  ,  sql  ,  database  ,  bw  ,  xml 3 - 6 yrs Gurgaon https://www.timesjobs.com/job-detail/business-data-analyst-green-tree-advisory-gurgaon-3-to-6-yrs-jobid-__SLASH__kuYVL79PqBzpSvf__PLUS__uAgZw==&source=srp
Randstad MENA business analysis   ,   report generation   ,   database management   ,   technical training   ,   communication skills   ,  python  ,  ms access  ,  bug fixing  ,  sql  ,  infrastructure 5 - 7 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-business-data-analyst-randstad-mena-bengaluru-bangalore-5-to-7-yrs-jobid-wg5DPCLtSHRzpSvf__PLUS__uAgZw==&source=srp
PUBLICIS GROUPE hive  ,  sql  ,  git  ,  hadoop  ,  python  ,  triggers  ,  messaging 8 - 11 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/lead-data-analyst-publicis-groupe-bengaluru-bangalore-8-to-11-yrs-jobid-W34jgTK6sC1zpSvf__PLUS__uAgZw==&source=srp
chqbook python  ,  big data  ,  mongodb  ,  sql 5 - 10 yr Gurgaon https://www.timesjobs.com/job-detail/data-analyst-tech-chqbook-gurgaon-5-to-10-yrs-jobid-anV6SIaOj__SLASH__tzpSvf__PLUS__uAgZw==&source=srp
ace softex pvt. ltd. css  ,  xml  ,  html 0 - 3 yrs Rajkot https://www.timesjobs.com/job-detail/data-analysts-html-editor-ace-softex-pvt-ltd-rajkot-0-to-3-yrs-jobid-wlDd24X5uGpzpSvf__PLUS__uAgZw==&source=srp
lyca digital pvt ltd communication  ,   comprehension  ,   sql  ,   t sql  ,   ssrs  ,   ssis  ,   msbi  ,   data analysis  ,   data reporting  ,   visualization tools   ,  t-sql  ,  salesforce 4 - 6 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/lycadigital-is-hiring-data-analyst-lyca-digital-pvt-ltd-bengaluru-bangalore-4-to-6-yrs-jobid-Mb5__PLUS__489oyWFzpSvf__PLUS__uAgZw==&source=srp
lyca digital pvt ltd communication  ,   comprehension  ,   sql  ,   t sql  ,   ssrs  ,   ssis  ,   msbi  ,   data analysis  ,   data reporting  ,   visualization tools   ,  t-sql  ,  salesforce 4 - 6 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/lycadigital-is-hiring-data-analyst-lyca-digital-pvt-ltd-bengaluru-bangalore-4-to-6-yrs-jobid-RuD4tnVcZ__SLASH__pzpSvf__PLUS__uAgZw==&source=srp
Nielsen Research Ltd. Co. data analysis   ,   sql   ,   data visualization   ,   aws cloud services   ,   communication skills   ,  bi  ,  data warehousing  ,  satellite  ,  big data  ,  python  ,  reporting tools 5 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/nielsen-data-analyst-nielsen-research-ltd-co-mumbai-5-to-8-yrs-jobid-zcNUCmGb__SLASH__ghzpSvf__PLUS__uAgZw==&source=srp
Alstom Projects India Ltd. statistical analysis  ,   database management  ,   electrical engineering  ,   interpersonal skills  ,   communication skills   ,  infrastructure 2 - 5 yrs  https://www.timesjobs.com/job-detail/reliability-data-analyst-alstom-projects-india-ltd-2-to-5-yrs-jobid-cys4loqvutpzpSvf__PLUS__uAgZw==&source=srp
ZeroFOX analytics   ,   data modeling   ,   sql   ,   statistics   ,   data storytelling   ,  bi  ,  salesforce  ,  security  ,  apache  ,  rest  ,  python  ,  team player 1 - 10 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/business-intelligence-data-analyst-zerofox-bengaluru-bangalore-1-to-10-yrs-jobid-7x6oQ7AoXRlzpSvf__PLUS__uAgZw==&source=srp
pratibha analytics bi  ,  hadoop  ,  pl  /  sql  ,  big data  ,  sql 1 - 6 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/senior-data-analysts-pratibha-analytics-hyderabad-secunderabad-1-to-6-yrs-jobid-THvRE__SLASH__nu4pRzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   data science  ,   business analytics  ,   report preparation  ,   academic publishing   ,  director 5 - 9 yrs Chennai https://www.timesjobs.com/job-detail/ra-data-analyst-engineer-anicalls-pty-ltd-chennai-5-to-9-yrs-jobid-Tl4tCGHemZJzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   data science  ,   business analytics  ,   report preparation  ,   academic publishing   ,  director 5 - 9 yrs Chennai https://www.timesjobs.com/job-detail/ra-data-analyst-engineer-anicalls-pty-ltd-chennai-5-to-9-yrs-jobid-QzF__SLASH__MTjq5C5zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   data science  ,   business analytics  ,   problem solving  ,   report writing   ,  director 5 - 9 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/ra-data-analyst-anicalls-pty-ltd-hyderabad-secunderabad-5-to-9-yrs-jobid-zfsNFDvTQh9zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   data science  ,   business analytics  ,   problem solving  ,   report writing   ,  director 5 - 9 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/ra-data-analyst-anicalls-pty-ltd-hyderabad-secunderabad-5-to-9-yrs-jobid-AbPkI44ZFfVzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   data science  ,   business analytics  ,   problem solving  ,   report preparation   ,  director 5 - 9 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-scientist-anicalls-pty-ltd-bengaluru-bangalore-5-to-9-yrs-jobid-CN9yhkg9GrtzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   data science  ,   business analytics  ,   problem solving  ,   report preparation   ,  director 5 - 9 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-scientist-anicalls-pty-ltd-bengaluru-bangalore-5-to-9-yrs-jobid-EN02DQdW43pzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   hypotheses  ,   reports  ,   data science  ,   analytics    ,  director  ,  business analytics 5 - 9 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/data-analyst-scientist-anicalls-pty-ltd-noida-greater-noida-5-to-9-yrs-jobid-c0Ia4lWKSnFzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd research  ,   hypotheses  ,   reports  ,   data science  ,   analytics    ,  director  ,  business analytics 5 - 9 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/data-analyst-scientist-anicalls-pty-ltd-noida-greater-noida-5-to-9-yrs-jobid-ulOJisH7XR9zpSvf__PLUS__uAgZw==&source=srp
grazitti interactive apache  ,  xml  ,  ssrs  ,  python  ,  oracle  ,  javascript  ,  business objects  ,  algorithms  ,  data mining  ,  bi  ,  sql  ,  hadoop  ,  sas  ,  written communication 6 - 9 yrs Mohali https://www.timesjobs.com/job-detail/lead-data-analyst-grazitti-interactive-mohali-6-to-9-yrs-jobid-YfRs3zR3rlBzpSvf__PLUS__uAgZw==&source=srp
nielsensports data analytics   ,   sql   ,   data warehousing   ,   dashboarding and reporting   ,   communication skills   ,  bi  ,  satellite  ,  big data  ,  cloud services  ,  python  ,  reporting tools 5 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/nielsen-data-analyst-nielsensports-mumbai-5-to-8-yrs-jobid-OQX__PLUS__MpOykxhzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd supply planning   ,   demand planning   ,   business analytics   ,   predictive modeling   ,   data mining   ,  data analysis  ,  business process 6 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/data-analyst-modeler-anicalls-pty-ltd-mumbai-6-to-8-yrs-jobid-KYk__SLASH__fFjE8rhzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd supply planning   ,   demand planning   ,   business analytics   ,   predictive modeling   ,   data mining   ,  data analysis  ,  business process 6 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/data-analyst-modeler-anicalls-pty-ltd-mumbai-6-to-8-yrs-jobid-RHF5aLAiymtzpSvf__PLUS__uAgZw==&source=srp
landis gyr ltd  ( noida ) system analysis   ,   design  &  development   ,   microsoft   ,  net framework   ,   web technologies   ,   sql query writing   ,  postgresql  ,  devops  ,  microsoft .net  ,  html  ,  pl  /  sql  ,  python  ,  oracle  ,  team player  ,  triggers  ,  javascript  ,  c# .net 7 - 12 yr Noida/Greater Noida https://www.timesjobs.com/job-detail/technical-lead-data-analyst-landis-gyr-ltd-noida-noida-greater-noida-7-to-12-yrs-jobid-WWtr2ONCJjFzpSvf__PLUS__uAgZw==&source=srp
landis gyr ltd  ( noida ) system analysis   ,   design  &  development   ,   microsoft   ,  net framework   ,   web technologies   ,   sql query writing   ,  postgresql  ,  devops  ,  microsoft .net  ,  html  ,  pl  /  sql  ,  python  ,  oracle  ,  team player  ,  triggers  ,  javascript  ,  c# .net 7 - 12 yr Noida/Greater Noida https://www.timesjobs.com/job-detail/technical-lead-data-analyst-landis-gyr-ltd-noida-noida-greater-noida-7-to-12-yrs-jobid-daXQCyK69ElzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data warehousing   ,   business intelligence   ,   analytical tools   ,   data pipelines   ,   data quality   ,  metadata  ,  bi  ,  security 5 - 9 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/data-analyst-software-engineer-anicalls-pty-ltd-hyderabad-secunderabad-5-to-9-yrs-jobid-34ULVe1rwEhzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data warehousing   ,   business intelligence   ,   analytical tools   ,   data pipelines   ,   data quality   ,  metadata  ,  bi  ,  security 5 - 9 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/data-analyst-software-engineer-anicalls-pty-ltd-hyderabad-secunderabad-5-to-9-yrs-jobid-AdXjgEF23ZBzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data reporting and analytics   ,   business intelligence   (  b  ,  i  ,    )     ,   data management   ,   etl and visualization tools   ,   project management   ,  accounting  ,  finance 5 - 8 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/data-analyst-tableau-anicalls-pty-ltd-hyderabad-secunderabad-5-to-8-yrs-jobid-8kOFr9FCXqtzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data reporting and analytics   ,   business intelligence   (  b  ,  i  ,    )     ,   data management   ,   etl and visualization tools   ,   project management   ,  accounting  ,  finance 5 - 8 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/data-analyst-tableau-anicalls-pty-ltd-hyderabad-secunderabad-5-to-8-yrs-jobid-MdVaFbCvK4xzpSvf__PLUS__uAgZw==&source=srp
ion trading india pvt. ltd. bi  ,  big data  ,  python  ,  information retrieval  ,  problem solving  ,  team player  ,  machine learning 2 - 3 yrs  https://www.timesjobs.com/job-detail/data-scientist-data-analyst-ion-trading-india-pvt-ltd-2-to-3-yrs-jobid-Ss5EzLERdpdzpSvf__PLUS__uAgZw==&source=srp
Larsen & Toubro Infotech Ltd java  ,   cloud migration  ,   windows  &  linux system management  ,   ci  /  cd tools  ,   java ee platforms   ,  hibernate  ,  sql  ,  database  ,  devops  ,  spring framework  ,  written communication 5 - 10 yr Mumbai https://www.timesjobs.com/job-detail/java-with-cloud-data-analyst-larsen-toubro-infotech-ltd-mumbai-5-to-10-yrs-jobid-PXPsjM__SLASH__0X5JzpSvf__PLUS__uAgZw==&source=srp
Larsen & Toubro Infotech Ltd java  ,   cloud migration  ,   windows  &  linux system management  ,   ci  /  cd tools  ,   java ee platforms   ,  hibernate  ,  sql  ,  database  ,  devops  ,  spring framework  ,  written communication 5 - 10 yr Mumbai https://www.timesjobs.com/job-detail/java-with-cloud-data-analyst-larsen-toubro-infotech-ltd-mumbai-5-to-10-yrs-jobid-XPhTIBRyveBzpSvf__PLUS__uAgZw==&source=srp
netskope software pvt.ltd data analysis   ,   strategic thinking   ,   leadership   ,   looker  /  tableau  /  power bi   ,   sql   ,  communication skills  ,  employee recognition 8 - 11 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-netskope-software-pvt-ltd-bengaluru-bangalore-8-to-11-yrs-jobid-bcCKzSDibjRzpSvf__PLUS__uAgZw==&source=srp
netskope software pvt.ltd data analysis   ,   data visualization   ,   sql   ,   leadership   ,   problem solving   ,  communication skills  ,  employee recognition 8 - 11 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-netskope-software-pvt-ltd-bengaluru-bangalore-8-to-11-yrs-jobid-g6l1KGYREoFzpSvf__PLUS__uAgZw==&source=srp
netskope software pvt.ltd data analysis   ,   strategic thinking   ,   leadership   ,   looker  /  tableau  /  power bi   ,   sql   ,  communication skills  ,  employee recognition 8 - 11 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-netskope-software-pvt-ltd-bengaluru-bangalore-8-to-11-yrs-jobid-x3__SLASH__L3aDBp__SLASH__5zpSvf__PLUS__uAgZw==&source=srp
aeries technology group  ( sabre industries ) reports  ,  conditional formatting  ,  accounting  ,  issue  ,  reconciliation  ,  excel  ,  financial operations  ,  accounts  ,  finance 1 - 3 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/financial-ops-data-analyst-aeries-technology-group-sabre-industries-bengaluru-bangalore-1-to-3-yrs-jobid-3SD0S2rJpd5zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis   ,   oracle pl  /  sql   ,   etl   ,   reporting and data visualization   ,   data warehousing   ,  tableau  ,  data analytics 5 - 9 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/data-analyst-developer-associate-anicalls-pty-ltd-noida-greater-noida-5-to-9-yrs-jobid-ceq1pLYB__PLUS__xlzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis   ,   oracle pl  /  sql   ,   etl   ,   reporting and data visualization   ,   data warehousing   ,  tableau  ,  data analytics 5 - 9 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/data-analyst-developer-associate-anicalls-pty-ltd-noida-greater-noida-5-to-9-yrs-jobid-VpLr0rGUmn1zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis and documentation   ,   oracle pl  /  sql   ,   etl and data warehousing   ,   reporting and data visualization   ,   gathering  ,   cleaning  ,   and transforming techniques   ,  tableau  ,  data analytics 5 - 9 yrs Chennai https://www.timesjobs.com/job-detail/sr-data-analyst-anicalls-pty-ltd-chennai-5-to-9-yrs-jobid-8nkQ1Xzj14NzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis and documentation   ,   oracle pl  /  sql   ,   etl and data warehousing   ,   reporting and data visualization   ,   gathering  ,   cleaning  ,   and transforming techniques   ,  tableau  ,  data analytics 5 - 9 yrs Chennai https://www.timesjobs.com/job-detail/sr-data-analyst-anicalls-pty-ltd-chennai-5-to-9-yrs-jobid-1hMJXVwDkl5zpSvf__PLUS__uAgZw==&source=srp
Randstad MENA data analysis   ,   bi tools   ,   code versioning   ,   software development life cycle   ,   data quality   ,  waterfall  ,  agile  ,  sdlc 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-telecom-randstad-mena-bengaluru-bangalore-5-to-8-yrs-jobid-VSgfsERNtPhzpSvf__PLUS__uAgZw==&source=srp
Randstad MENA data analysis   ,   sql   ,   snowflake   ,   data visualization   ,   ux testing   ,  bi  ,  qa  ,  usability  ,  ui 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-randstad-mena-bengaluru-bangalore-5-to-8-yrs-jobid-XizZdpWNzWRzpSvf__PLUS__uAgZw==&source=srp

anicalls pty ltd data analysis  r  ,   python  ,   sas  ,   matlab  ,   java  hive  ,   spark  ,   scala  ,   javascript  ,   sql  building cloud applications  aws cloud services   ,  css  ,  machine learning  ,  apache  ,  html  ,  hadoop  ,  big data 6 - 8 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/aws-data-analyst-anicalls-pty-ltd-hyderabad-secunderabad-6-to-8-yrs-jobid-usjXtWAqH__SLASH__NzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis  r  ,   python  ,   sas  ,   matlab  ,   java  hive  ,   spark  ,   scala  ,   javascript  ,   sql  building cloud applications  aws cloud services   ,  css  ,  machine learning  ,  apache  ,  html  ,  hadoop  ,  big data 6 - 8 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/aws-data-analyst-anicalls-pty-ltd-hyderabad-secunderabad-6-to-8-yrs-jobid-wY3h__SLASH__aEwt0FzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis   ,   programming   ,   cloud applications   ,   aws cloud services   ,   big data and machine learning   ,  hive  ,  python  ,  css  ,  sas  ,  scala  ,  javascript  ,  sql  ,  apache  ,  html  ,  hadoop 6 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/aws-data-analyst-engineer-anicalls-pty-ltd-mumbai-6-to-8-yrs-jobid-YG1Ljuu1eoRzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis   ,   programming   ,   cloud applications   ,   aws cloud services   ,   big data and machine learning   ,  hive  ,  python  ,  css  ,  sas  ,  scala  ,  javascript  ,  sql  ,  apache  ,  html  ,  hadoop 6 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/aws-data-analyst-engineer-anicalls-pty-ltd-mumbai-6-to-8-yrs-jobid-thOW23FAsflzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd maintain data models  ,   communicate changes  ,   resolve data questions  ,   etl scripts  ,   load data   ,  maintenance 5 - 9 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/oracle-data-analyst-anicalls-pty-ltd-noida-greater-noida-5-to-9-yrs-jobid-gtDhY6jnttZzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd maintain data models  ,   communicate changes  ,   resolve data questions  ,   etl scripts  ,   load data   ,  maintenance 5 - 9 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/oracle-data-analyst-anicalls-pty-ltd-noida-greater-noida-5-to-9-yrs-jobid-d3jVE4ABUidzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd azure data factory   ,   azure databricks   ,   python  ,   scala  ,   pyspark  ,   spark   ,   hive   /   hive llap   /   hbase   /   cosmodb   ,   azure active directory domain services   ,  apache 8 - 12 yr Noida/Greater Noida https://www.timesjobs.com/job-detail/azure-big-data-analyst-anicalls-pty-ltd-noida-greater-noida-8-to-12-yrs-jobid-zM__SLASH__EUi4jB8NzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd azure data factory   ,   azure databricks   ,   python  ,   scala  ,   pyspark  ,   spark   ,   hive   /   hive llap   /   hbase   /   cosmodb   ,   azure active directory domain services   ,  apache 8 - 12 yr Noida/Greater Noida https://www.timesjobs.com/job-detail/azure-big-data-analyst-anicalls-pty-ltd-noida-greater-noida-8-to-12-yrs-jobid-92LR1u5ZT0FzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis   ,   oracle pl  /  sql   ,   etl   ,   data warehouse   ,   data visualization   ,  tableau  ,  data analytics  ,  data warehousing 5 - 9 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-anicalls-pty-ltd-bengaluru-bangalore-5-to-9-yrs-jobid-vWSscatWcixzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis   ,   oracle pl  /  sql   ,   etl   ,   data warehouse   ,   data visualization   ,  tableau  ,  data analytics  ,  data warehousing 5 - 9 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-data-analyst-anicalls-pty-ltd-bengaluru-bangalore-5-to-9-yrs-jobid-TulOxl__PLUS__VnkZzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd cloud data analytics   (  aws  ,   oracle  ,   azure  ,   snowflake  )     ,   solution design   ,   account management   ,   big data   ,   it strategy   ,  mining 8 - 10 yr Chennai https://www.timesjobs.com/job-detail/dw-and-big-data-analyst-anicalls-pty-ltd-chennai-8-to-10-yrs-jobid-ZOazYDX8gTNzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd cloud data analytics   (  aws  ,   oracle  ,   azure  ,   snowflake  )     ,   solution design   ,   account management   ,   big data   ,   it strategy   ,  mining 8 - 10 yr Chennai https://www.timesjobs.com/job-detail/dw-and-big-data-analyst-anicalls-pty-ltd-chennai-8-to-10-yrs-jobid-BHxGA6KaIiVzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd erp management   ,   data analysis   ,   data quality improvement   ,   data governance   ,   process control   ,  process design 6 - 9 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/master-data-analyst-anicalls-pty-ltd-noida-greater-noida-6-to-9-yrs-jobid-5tWgywryaTNzpSvf__PLUS__uAgZw==&source=srp
Rimini Street information technology  ,  artificial intelligence  ,  salesforce  ,  oracle  ,  ms access  ,  web technologies  ,  software support  ,  data mining  ,  sharepoint  ,  sql  ,  database  ,  problem solving  ,  application management 4 - 7 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/business-data-analyst-rimini-street-hyderabad-secunderabad-4-to-7-yrs-jobid-vG2kALgMr1FzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis   ,   jde reporting   ,   sql server   ,   ssis   ,   ssrs   ,  c# 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-jd-edwards-anicalls-pty-ltd-bengaluru-bangalore-5-to-8-yrs-jobid-wwN48PLXusNzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd business analysis   ,   data analysis   ,   sql   ,   excel   ,   communication   ,  business rules  ,  database  ,  oracle  ,  problem solving 5 - 10 yr Mumbai https://www.timesjobs.com/job-detail/data-analyst-sap-hana-anicalls-pty-ltd-mumbai-5-to-10-yrs-jobid-fGxI4pjLaC5zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd business analysis   ,   data lineage   ,   sql   ,   excel   ,   database knowledge   ,  business rules  ,  oracle  ,  problem solving 5 - 10 yr Chennai https://www.timesjobs.com/job-detail/sap-hana-data-analyst-anicalls-pty-ltd-chennai-5-to-10-yrs-jobid-sneqrVTAIlVzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd business analysis   ,   data analysis   ,   sql   ,   excel   ,   communication   ,  business rules  ,  database  ,  oracle  ,  problem solving 5 - 10 yr Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/data-analyst-with-sap-hana-anicalls-pty-ltd-hyderabad-secunderabad-5-to-10-yrs-jobid-ve1FQXDNjwVzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd communication skills   ,   collaboration   ,   code development   ,   shell scripting   ,   python  /  r   ,  hive  ,  sas  ,  oozie  ,  git  ,  written communication  ,  software support  ,  hadoop  ,  sqoop  ,  hbase 5 - 10 yr Noida/Greater Noida https://www.timesjobs.com/job-detail/sr-big-data-analyst-anicalls-pty-ltd-noida-greater-noida-5-to-10-yrs-jobid-B3m6KUpfdNZzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      project  ,  data analysis 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-LCdFFwT3bFpzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      computer operator  ,  computer operator  ,  system administrator 2 - 5 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-delhi-andaman-nicobar-dadra-nagar-haveli-silvassa-daman-diu-2-to-5-yrs-jobid-J4d__SLASH__s2H3DJNzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      computer operator  ,  computer operator  ,  system administrator 2 - 5 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-delhi-andaman-nicobar-dadra-nagar-haveli-silvassa-daman-diu-2-to-5-yrs-jobid-IkId9cTPFjhzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      jobs  ,  freshers  ,  data analyst 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-jalgaon-kolhapur-nagpur-solapur-0-to-1-yrs-jobid-YRe9SImISa5zpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analyst  ,  navi mumbai 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-u7uuvaDGNsJzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analyst  ,  mumbai  ,  freshers 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-dombivali-kalyan-navi-mumbai-thane-0-to-1-yrs-jobid-4oJzsCvmlNVzpSvf__PLUS__uAgZw==&source=srp

Maxgen Technologies
      pune  ,  data analyst 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-amravati-aurangabad-sangli-satara-0-to-1-yrs-jobid-__SLASH__ptzbF5gZ9xzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analyst  ,  engineer 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-jalgaon-kolhapur-nagpur-solapur-0-to-1-yrs-jobid-b__SLASH__fk29OnaZhzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      . 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-at-pune-maxgen-technologies-pune-jalgaon-kolhapur-nagpur-solapur-0-to-1-yrs-jobid-VYYJcpGJTO9zpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analyst  ,  software engineer 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-amravati-aurangabad-sangli-satara-0-to-1-yrs-jobid-jGGLP7AkWZ1zpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      computer operator  ,  computer operator  ,  system administrator 2 - 5 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-delhi-andaman-nicobar-dadra-nagar-haveli-silvassa-daman-diu-2-to-5-yrs-jobid-5RkA9H__PLUS__1uKJzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      programming 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-at-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-WrwbWyx7AiZzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      analyst 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-jalgaon-kolhapur-nagpur-solapur-0-to-1-yrs-jobid-__SLASH__PQxzr8Z8pNzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      jobs  ,  data anlayst 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-4f5sDakVHlhzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      internship  ,  data anlayst  ,  intern 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-kalyan-nasik-navi-mumbai-thane-0-to-1-yrs-jobid-ciJVZguVcX1zpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      learn  ,  internship  ,  data analyst  ,  analyst 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-mumbai-maxgen-technologies-mumbai-dombivali-kalyan-navi-mumbai-thane-0-to-1-yrs-jobid-LCYXFtz78PxzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      hire  ,  data anlayst  ,  intern 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-jalgaon-kolhapur-nagpur-solapur-0-to-1-yrs-jobid-eVOBhb0a90ZzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      data entry operator  ,  computer operator  ,  system administrator 1 - 3 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-cuddapah-guntakal-godhra-bhiwani-1-to-3-yrs-jobid-yth7JytojZNzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      data entry operator  ,  computer operator  ,  system administrator 1 - 3 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-cuddapah-guntakal-godhra-bhiwani-1-to-3-yrs-jobid-Rqc3DMw__PLUS__vftzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      data entry operator  ,  computer operator  ,  system administrator 1 - 3 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-cuddapah-guntakal-godhra-bhiwani-1-to-3-yrs-jobid-23C7HY8WvcFzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      data entry operator  ,  computer operator  ,  system administrator 1 - 5 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-kolkata-pune-rewari-bikaner-jaipur-1-to-5-yrs-jobid-ovBAduXIwoJzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      computer operator  ,  computer operator  ,  system administrator 2 - 5 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-delhi-andaman-nicobar-dadra-nagar-haveli-silvassa-daman-diu-2-to-5-yrs-jobid-Fb8g7hs2fjJzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      computer operator  ,  computer operator  ,  system administrator 2 - 5 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-delhi-andaman-nicobar-dadra-nagar-haveli-silvassa-daman-diu-2-to-5-yrs-jobid-Bv8KUsplk__SLASH__hzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      engineer  ,  internship 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-in-pune-maxgen-technologies-pune-amravati-aurangabad-sangli-satara-0-to-1-yrs-jobid-viF0oTyw5XtzpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      data entry operator  ,  computer operator  ,  system administrator 1 - 4 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-bengaluru-bangalore-anantapur-srikakulam-jorhat-bhilai-durg-1-to-4-yrs-jobid-dqmGMJv0puhzpSvf__PLUS__uAgZw==&source=srp
Maxgen Technologies
      data analysis 0 - 1 yrs   https://www.timesjobs.com/job-detail/data-analyst-internship-maxgen-technologies-pune-jalgaon-kolhapur-nagpur-solapur-0-to-1-yrs-jobid-VUt31bwY6K1zpSvf__PLUS__uAgZw==&source=srp
RRL Staffing
      data entry operator  ,  computer operator  ,  system administrator 1 - 4 yrs   https://www.timesjobs.com/job-detail/data-analyst-programmer-rrl-staffing-bengaluru-bangalore-anantapur-srikakulam-jorhat-bhilai-durg-1-to-4-yrs-jobid-N9nnuzdLzPpzpSvf__PLUS__uAgZw==&source=srp
Netxcell Ltd data analytics  ,  c  ,  computer application  ,  data analyst 3 - 6 yrs Vijayawada https://www.timesjobs.com/job-detail/business-data-analyst-bda-application-netxcell-ltd-vijayawada-3-to-6-yrs-jobid-ixROmLwuty5zpSvf__PLUS__uAgZw==&source=srp
Veeva Systems visualization  ,  data analytics  ,  customer success  ,  mx  ,  ehr  ,  bi  ,  emr  ,  sql  ,  san  ,  spotfire  ,  data analyst  ,  tableau 4 - 7 yrs New York City https://www.timesjobs.com/job-detail/senior-healthcare-data-analyst-safemine-veeva-systems-new-york-city-4-to-7-yrs-jobid-DwgQD8oRBCxzpSvf__PLUS__uAgZw==&source=srp
Veeva Systems visualization  ,  data analytics  ,  customer success  ,  mx  ,  ehr  ,  bi  ,  emr  ,  sql  ,  san  ,  spotfire  ,  data analyst  ,  tableau 4 - 7 yrs Boston https://www.timesjobs.com/job-detail/senior-healthcare-data-analyst-safemine-veeva-systems-boston-4-to-7-yrs-jobid-TF7g4FIvSt9zpSvf__PLUS__uAgZw==&source=srp
ion trading india pvt. ltd. data analysis   ,   powerbi   ,   etl   ,   communication   ,   infrastructure systems    ,  hosting  ,  dashboards  ,  technology infrastructure  ,  electronic trading  ,  consulting  ,  data analyst  ,  written communication 3 - 5 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/ion-group-data-analyst-9839-ion-trading-india-pvt-ltd-noida-greater-noida-3-to-5-yrs-jobid-qRTTu2uR3EtzpSvf__PLUS__uAgZw==&source=srp
CAMBRIDGE TECHNOLOGY INDIA PVT LTD visualization  ,  information technology  ,  data mining  ,  sql  ,  java  ,  business process improvement  ,  data analytics  ,  data analysis  ,  consulting  ,  business analysis  ,  mining  ,  data analyst  ,  business intelligence reporting  ,  tableau  ,  predictive modeling  ,  statistical analysis 2 - 6 yrs  https://www.timesjobs.com/job-detail/senior-data-analyst-remote-preferable-cambridge-technology-india-pvt-ltd-2-to-6-yrs-jobid-UbZyj6vjGJVzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd 1  )   tableau  ,   excel 2  )   sql queries 3  )   python scripting 4  )   data visualization 5  )   data analysis   ,  business requirements  ,  business analyst  ,  security  ,  data science  ,  data analytics  ,  business environment  ,  data analyst  ,  alteryx  ,  ms office suite 5 - 10 yr Mumbai https://www.timesjobs.com/job-detail/sr-business-systems-data-analyst-anicalls-pty-ltd-mumbai-5-to-10-yrs-jobid-kjnZRSaExhlzpSvf__PLUS__uAgZw==&source=srp
BUSISOL SOURCING INDIA PVT. LTD dispatch  ,  transporters  ,  inventory  ,  customs  ,  freight forwarding  ,  price negotiation  ,  dispatch planning  ,  transportation 5 - 7 yrs Mumbai https://www.timesjobs.com/job-detail/operation-executive-cum-data-analyst-busisol-sourcing-india-pvt-ltd-mumbai-5-to-7-yrs-jobid-eGrWA7nyw9ZzpSvf__PLUS__uAgZw==&source=srp
palo alto networks  ( india )  pvt. ltd. data extraction   ,   sql   ,   data analysis   ,   business intelligence   ,   financial planning   ,  learning  ,  leave  ,  decision making 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/senior-data-analyst-cloud-finance-palo-alto-networks-india-pvt-ltd-bengaluru-bangalore-5-to-8-yrs-jobid-mRNozjiMCXFzpSvf__PLUS__uAgZw==&source=srp
Clarivate Analytics pharmaceutical market research   ,   analyzing complex datasets   ,   excellent attention to detail   ,   outstanding communication skills   ,   project management   ,  medical  ,  primary market research  ,  business insights  ,  website  ,  primary research 4 - 7 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/healthcare-research-data-analyst-clarivate-analytics-noida-greater-noida-4-to-7-yrs-jobid-3wUVq__PLUS__ObpLVzpSvf__PLUS__uAgZw==&source=srp
Paytm data analysis   ,   sql   ,   predictive modeling   ,   business intelligence   ,   communication   ,  reports  ,  accounting  ,  commerce  ,  reporting  ,  excel  ,  finance 3 - 5 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/paytm-data-analyst-sql-manager-paytm-noida-greater-noida-3-to-5-yrs-jobid-RznCUkaDFCxzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis and documentation   ,   oracle pl  /  sql   ,   etl  ,   data warehouse  ,   and data analytics   ,   reporting and data visualization   ,   data warehousing and etl techniques   ,  tableau 5 - 9 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/sr-data-analyst-software-engineer-anicalls-pty-ltd-hyderabad-secunderabad-5-to-9-yrs-jobid-EvbEdgE2fNxzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis and documentation   ,   oracle pl  /  sql   ,   etl  ,   data warehouse  ,   and data analytics   ,   reporting and data visualization   ,   data warehousing and etl techniques   ,  tableau 5 - 9 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/sr-data-analyst-software-engineer-anicalls-pty-ltd-hyderabad-secunderabad-5-to-9-yrs-jobid-g3OoBRCT0__PLUS__RzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd sql scripting   ,   sas scripting   ,   data analysis   ,   m  ,  s  ,   excel   ,   relational database   ,  testing  ,  test cases  ,  test scripts  ,  unix  ,  healthcare 5 - 7 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/data-analyst-sas-sql-macros-anicalls-pty-ltd-noida-greater-noida-5-to-7-yrs-jobid-SvJARUTV__SLASH__IxzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd sql scripting   ,   sas scripting   ,   data analysis   ,   m  ,  s  ,   excel   ,   relational database   ,  testing  ,  test cases  ,  test scripts  ,  unix  ,  healthcare 5 - 7 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/data-analyst-sas-sql-macros-anicalls-pty-ltd-noida-greater-noida-5-to-7-yrs-jobid-LeDX6GQRAQZzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd business analysis   ,   requirements gathering   ,   data analysis   ,   sql   ,   excel    ,  business rules  ,  database  ,  oracle  ,  problem solving 5 - 10 yr Bengaluru / Bangalore https://www.timesjobs.com/job-detail/sr-sap-hana-data-analyst-anicalls-pty-ltd-bengaluru-bangalore-5-to-10-yrs-jobid-Gv7XNlfQcTJzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd business analysis   ,   data analysis   ,   sql   ,   excel   ,   communication skills   ,  business rules  ,  database  ,  oracle  ,  problem solving 5 - 10 yr Noida/Greater Noida https://www.timesjobs.com/job-detail/senior-data-analyst-with-sap-hana-anicalls-pty-ltd-noida-greater-noida-5-to-10-yrs-jobid-b8efhDl4__SLASH__lFzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data analysis  ,   jde reports  ,   sql server  ,   ssis  ,   ssrs   ,  c# 5 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/data-analyst-with-jd-edwards-engineer-anicalls-pty-ltd-mumbai-5-to-8-yrs-jobid-kKRrx6r__SLASH__0LNzpSvf__PLUS__uAgZw==&source=srp
HR Jobs Placements
      Data Warehousing  ,  Data Analysis  ,  new program launches  ,  SLA  ,  Team Management  ,  crawling  /  web scraping  ,   Data Modeling   ,  ETL development  ,  Java  ,  scala   ,  big data technologies 11 - 16 y   https://www.timesjobs.com/job-detail/big-data-analyst-hr-jobs-placements-bengaluru-bangalore-delhi-ncr-hyderabad-secunderabad-kolkata-mumbai-11-to-16-yrs-jobid-vduNjE7D04hzpSvf__PLUS__uAgZw==&source=srp
White Horse Manpower Consultancy P Ltd
      SQL  ,   IBM Cognos  ,   Spotfire  ,   Knowledge of Scripting   (  XML  ,   Java Script  ,   Shell Scripting  ,   Perl etc  ) 2 - 7 yrs   https://www.timesjobs.com/job-detail/aco-data-analyst-call-rina-white-horse-manpower-consultancy-p-ltd-bengaluru-bangalore-2-to-7-yrs-jobid-__PLUS__xI6yzPKYmJzpSvf__PLUS__uAgZw==&source=srp
AppSoft Solutions
      Data Analyst  ,   Senior Data Analyst  ,   Data Analyst - Tech Lead  ,  data profiling  ,  data models  ,  data collection 0 - 3 yrs   https://www.timesjobs.com/job-detail/data-analyst-senior-data-analyst-data-analyst-appsoft-solutions-ahmedabad-bengaluru-bangalore-chennai-delhi-delhi-ncr-0-to-3-yrs-jobid-wcZ__SLASH__KEwZAgtzpSvf__PLUS__uAgZw==&source=srp
BOSTON SCIENTIFIC visualization  ,  business requirements  ,  bi  ,  dashboards  ,  sql  ,  security  ,  database  ,  debugging  ,  data visualization  ,  data analytics  ,  data analysis  ,  data analyst  ,  tableau 5 - 8 yrs China https://www.timesjobs.com/job-detail/it-associate-it-manager-data-analyst-boston-scientific-china-5-to-8-yrs-jobid-pP2lyCeFHeBzpSvf__PLUS__uAgZw==&source=srp
crescendo global survey programming  ,   data analysis  ,   spss  ,   data processing  ,   sql   ,  dashboards  ,  java  ,  customer analytics  ,  data analytics  ,  consulting  ,  business analytics  ,  data analyst 5 - 8 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-survey-5-years-job-in-chennai-crescendo-global-chennai-5-to-8-yrs-jobid-g6ZIN6xEqJNzpSvf__PLUS__uAgZw==&source=srp
buck global llc data analysis   ,   data visualization   ,   cloud architecture   ,   python   ,   sql   ,  bi  ,  dashboards  ,  security  ,  use cases  ,  consulting  ,  data analyst  ,  tableau  ,  business process 2 - 3 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/de-jobs-qualcomm-data-analyst-in-noida-india-buck-global-llc-noida-greater-noida-2-to-3-yrs-jobid-OGEJHXxil8pzpSvf__PLUS__uAgZw==&source=srp
buck global llc data analysis   ,   data visualization   ,   cloud architecture   ,   python coding   ,   sql coding   ,  bi  ,  dashboards  ,  security  ,  use cases  ,  consulting  ,  data analyst  ,  tableau  ,  business process 2 - 3 yrs Chennai https://www.timesjobs.com/job-detail/de-jobs-qualcomm-data-analyst-in-chennai-india-buck-global-llc-chennai-2-to-3-yrs-jobid-p0Na7ykRWyNzpSvf__PLUS__uAgZw==&source=srp
buck global llc data analytics   ,   data visualization   ,   cloud architecture   ,   hr analytics   ,   tableau   ,  information technology  ,  bi  ,  data warehousing  ,  dashboards  ,  sql  ,  security  ,  data science  ,  data analysis  ,  information management  ,  consulting  ,  data analyst  ,  business process 3 - 5 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/de-jobs-qualcomm-data-analyst-in-noida-india-buck-global-llc-noida-greater-noida-3-to-5-yrs-jobid-nJcK0omzahlzpSvf__PLUS__uAgZw==&source=srp
celanese india ltd data analytics   ,   process automation   ,   internal audit   ,   alteryx   ,   sql   ,  bi  ,  data science  ,  data visualization  ,  data analysis  ,  data analyst  ,  tableau  ,  vba  ,  written communication 5 - 8 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/sr-data-analyst-automation-internal-audit-celanese-india-ltd-hyderabad-secunderabad-5-to-8-yrs-jobid-PHgYizcCgzZzpSvf__PLUS__uAgZw==&source=srp
celanese india ltd data analytics   ,   process automation   ,   internal audit   ,   alteryx   ,   sql   ,  bi  ,  data science  ,  data visualization  ,  data analysis  ,  data analyst  ,  tableau  ,  vba  ,  written communication 5 - 8 yrs Hyderabad/Secunderabad https://www.timesjobs.com/job-detail/sr-data-analyst-automation-internal-audit-celanese-india-ltd-hyderabad-secunderabad-5-to-8-yrs-jobid-bJh57tYHQWpzpSvf__PLUS__uAgZw==&source=srp
netskope software pvt.ltd data analysis   ,   sql   ,   tableau   ,   looker   ,   python   ,  soft skills  ,  employee recognition 0 - 1 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/intern-cso-data-analyst-summer-2024-netskope-software-pvt-ltd-bengaluru-bangalore-0-to-1-yrs-jobid-MiZw2Xj48QhzpSvf__PLUS__uAgZw==&source=srp
BUSISOL SOURCING INDIA PVT. LTD r2  ,  information technology  ,  dbms  ,  t-sql  ,  xml  ,  ssrs  ,  c#  ,  triggers  ,  .net  ,  microsoft technologies  ,  bi  ,  sql  ,  t - sql  ,  sql developer  ,  rdbms  ,  production support 6 - 8 yrs Mumbai https://www.timesjobs.com/job-detail/power-bi-sql-tableau-developer-data-analyst-busisol-sourcing-india-pvt-ltd-mumbai-6-to-8-yrs-jobid-MxHBNBnI__PLUS____SLASH__BzpSvf__PLUS__uAgZw==&source=srp

hitachi ltd data analytics   ,   technical expertise   ,   power bi   ,   machine learning   ,   sql database   ,  ensemble  ,  dashboards  ,  data science  ,  data visualization  ,  data analysis  ,  artificial neural networks  ,  tableau  ,  hitachi  ,  data cleaning 2 - 5 yrs Chennai https://www.timesjobs.com/job-detail/engineering-data-analyst-in-chennai-tn-hitachi-hitachi-ltd-chennai-2-to-5-yrs-jobid-rYVcbkg8E__PLUS__VzpSvf__PLUS__uAgZw==&source=srp
smartSense Consulting Solutions web analysis  ,  bi  ,  data warehousing  ,  data architecture  ,  business intelligence  ,  database  ,  bi developer  ,  etl  ,  data profiling  ,  ssas  ,  infrastructure  ,  olap  ,  sql programming 2 - 4 yrs Gandhinagar https://www.timesjobs.com/job-detail/sr-data-analyst-power-bi-developer-smartsense-consulting-solutions-gandhinagar-2-to-4-yrs-jobid-omk3uOZoc31zpSvf__PLUS__uAgZw==&source=srp
ANZ GRINDLAYS BANK data analysis   ,   financial modelling   ,   predictive modeling   ,   customer engagement   ,   data visualization   ,  job posting  ,  leave  ,  communication  ,  presentation skills  ,  decision making  ,  recruitment process 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-ind-blr-grp-4-4-anz-grindlays-bank-bengaluru-bangalore-5-to-8-yrs-jobid-3aVg0Apnh9ZzpSvf__PLUS__uAgZw==&source=srp
zf india pvt ltd ms powerbi dashboard  ,   data analysis  ,   data visualization  ,   business requirements gathering  ,   power query   ,  sql  ,  database 4 - 7 yrs Chennai https://www.timesjobs.com/job-detail/it-data-analyst-ms-powerbi-dashboard-zf-india-pvt-ltd-chennai-4-to-7-yrs-jobid-2jaOtS0v__SLASH__NhzpSvf__PLUS__uAgZw==&source=srp
Clarivate Analytics healthcare research   ,   data analysis   ,   api integration   ,   leadership   ,   sql   ,  security  ,  database  ,  software engineering  ,  big data  ,  leadership skills 4 - 7 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/senior-healthcare-research-data-analyst-clarivate-analytics-bengaluru-bangalore-4-to-7-yrs-jobid-DcYwKhralxdzpSvf__PLUS__uAgZw==&source=srp
SDL Multilingual Solutions Pvt Ltd data analysis   ,   data visualization   ,   oil and gas industry   ,   chemical engineering   ,   aspen one process explorer   ,  graphics  ,  technology operations  ,  digitization  ,  technology infrastructure  ,  cloud services  ,  team player 3 - 5 yrs Indore https://www.timesjobs.com/job-detail/deltek-talent-management-data-analyst-1108-8-sdl-multilingual-solutions-pvt-ltd-indore-3-to-5-yrs-jobid-cJM49jQ7HSxzpSvf__PLUS__uAgZw==&source=srp
SDL Multilingual Solutions Pvt Ltd data analysis   ,   data visualization   ,   oil and gas industry   ,   chemical engineering   ,   aspen one process explorer   ,  graphics  ,  technology operations  ,  digitization  ,  technology infrastructure  ,  cloud services  ,  team player 3 - 5 yrs Indore https://www.timesjobs.com/job-detail/deltek-talent-management-data-analyst-1108-8-sdl-multilingual-solutions-pvt-ltd-indore-3-to-5-yrs-jobid-yaV3HeXd4jxzpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data reporting and analytics  ,   business intelligence  ,   data management  ,   etl and visualization tools  ,   sas application   ,  accounting  ,  finance 5 - 8 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-tableau-power-b-i-consultant-anicalls-pty-ltd-chennai-5-to-8-yrs-jobid-9Nmt4GcMC75zpSvf__PLUS__uAgZw==&source=srp
anicalls pty ltd data reporting and analytics  ,   business intelligence  ,   data management  ,   etl and visualization tools  ,   sas application   ,  accounting  ,  finance 5 - 8 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-tableau-power-b-i-consultant-anicalls-pty-ltd-chennai-5-to-8-yrs-jobid-WQq69sOCszJzpSvf__PLUS__uAgZw==&source=srp
Clarivate Analytics healthcare  ,   life sciences  ,   quantitative analysis  ,   collaboration  ,   communication   ,  communication skills  ,  compensation 4 - 7 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/lead-healthcare-research-data-analyst-clarivate-analytics-bengaluru-bangalore-4-to-7-yrs-jobid-hQBiu33LI2JzpSvf__PLUS__uAgZw==&source=srp
SAMPOORNA CONSULTANTS PVT LTD
      Tableau 2 - 4 yrs   https://www.timesjobs.com/job-detail/data-analyst-tableau-developer-j47101-a-leading-firm-pune-2-to-4-yrs-jobid-zxWSxn4nxgBzpSvf__PLUS__uAgZw==&source=srp
buck global llc data analysis  &  reporting   ,   merchandise planning  /  operations   ,   buying   ,   digital operations   ,   project management   ,  business analyst  ,  data analyst  ,  business process 4 - 9 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/de-jobs-target-item-data-analyst-in-bengaluru-india-buck-global-llc-bengaluru-bangalore-4-to-9-yrs-jobid-2dTLJI39CaBzpSvf__PLUS__uAgZw==&source=srp
GROUPON sql   ,   tableau   ,   data analysis   ,   business intelligence   ,   fraud prevention    ,  visualization  ,  bi  ,  dashboards  ,  data analytics  ,  data analyst  ,  mobile commerce 3 - 6 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-fraud-payments-reporting-in-chennai-groupon-careers-groupon-chennai-3-to-6-yrs-jobid-914P5qsMqb9zpSvf__PLUS__uAgZw==&source=srp
GROUPON sql   ,   tableau   ,   data analysis   ,   business intelligence   ,   fraud prevention    ,  visualization  ,  bi  ,  dashboards  ,  data analytics  ,  data analyst  ,  mobile commerce 3 - 6 yrs Chennai https://www.timesjobs.com/job-detail/data-analyst-fraud-payments-reporting-in-chennai-groupon-careers-groupon-chennai-3-to-6-yrs-jobid-1GewBbaZs6hzpSvf__PLUS__uAgZw==&source=srp
buck global llc data analysis   ,   data visualization   ,   cloud architecture   ,   tableau dashboards   ,   hr analytics   ,  bi  ,  security  ,  use cases  ,  consulting  ,  data analyst  ,  business process 5 - 8 yrs Noida/Greater Noida https://www.timesjobs.com/job-detail/de-jobs-qualcomm-data-analyst-staff-in-noida-india-buck-global-llc-noida-greater-noida-5-to-8-yrs-jobid-Glu0cU2NE0dzpSvf__PLUS__uAgZw==&source=srp
crescendo global data analyst  ,   power bi  ,   dax  ,   data visualization  ,   data modelling  ,   data assimilation   ,  data mining  ,  dashboards  ,  data analytics  ,  consulting  ,  business analytics  ,  tableau 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-power-bi-8-years-bangalore-job-in-bengaluru-crescendo-global-bengaluru-bangalore-5-to-8-yrs-jobid-2vtFVROlLJZzpSvf__PLUS__uAgZw==&source=srp
crescendo global data analyst  ,   power bi  ,   dax  ,   data visualization  ,   data modelling  ,   data assimilation   ,  data mining  ,  dashboards  ,  data analytics  ,  consulting  ,  business analytics  ,  tableau 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/data-analyst-power-bi-8-years-bangalore-job-in-bengaluru-crescendo-global-bengaluru-bangalore-5-to-8-yrs-jobid-XLovjaY8g35zpSvf__PLUS__uAgZw==&source=srp
buck global llc data analysis   ,   statistical techniques   ,   data validation   ,   data visualization   ,   technical support   ,  spss  ,  dashboards  ,  security  ,  data science  ,  data analyst 5 - 8 yrs Delhi,  Delhi/NCR https://www.timesjobs.com/job-detail/de-jobs-jhpiego-data-analyst-in-new-delhi-india-buck-global-llc-delhi-delhi-ncr-5-to-8-yrs-jobid-DAjlV__PLUS__9KzalzpSvf__PLUS__uAgZw==&source=srp
crescendo global alteryx  ,   sql  ,   data visualization  ,   data cleaning  ,   data manipulation   ,  data mining  ,  bi  ,  spss  ,  data extraction  ,  xml  ,  data analytics  ,  sas  ,  data analyst  ,  tableau  ,  business objects 3 - 7 yrs Gurgaon https://www.timesjobs.com/job-detail/data-analyst-alteryx-sql-data-visualization-3-7-years-gurgaon-crescendo-global-gurgaon-3-to-7-yrs-jobid-dlcJPJ0s2PxzpSvf__PLUS__uAgZw==&source=srp
dun and bradstreet india pvt ltd ms office   (  excel  ,   word  ,   powerpoint  )     ,   verbal and written communication in english   ,   content writing   ,   analytical and reasoning capabilities   ,  data analysis  ,  data analyst 1 - 3 yrs Mumbai https://www.timesjobs.com/job-detail/dun-bradstreet-data-analyst-third-party-payroll-dun-and-bradstreet-india-pvt-ltd-mumbai-1-to-3-yrs-jobid-z7nfDWQS4E9zpSvf__PLUS__uAgZw==&source=srp
iron mountain india pvt ltd data analytics  ,   data science  ,   computer science  ,   excel  /  google sheets  ,   financial analysis   ,  storage  ,  dashboards  ,  macros  ,  information management  ,  data analyst 2 - 3 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/iron-mountain-jobs-data-analyst-global-commercial-support-in-bangalore-india-iron-mountain-india-pvt-ltd-bengaluru-bangalore-2-to-3-yrs-jobid-LMarMbWBauxzpSvf__PLUS__uAgZw==&source=srp
buck global llc systems governance   ,   manages ambiguity   ,   collaborates   ,   communicates effectively   ,   resourcefulness   ,  information technology  ,  pmp  ,  functional requirements  ,  data analytics  ,  system administration  ,  database  ,  data extraction  ,  security  ,  business analysis  ,  data analyst  ,  written communication 2 - 5 yrs Pune https://www.timesjobs.com/job-detail/de-jobs-cummins-inc-data-analyst-risk-insurance-in-pune-india-buck-global-llc-pune-2-to-5-yrs-jobid-700oTSNwQzNzpSvf__PLUS__uAgZw==&source=srp
iron mountain india pvt ltd data analysis  ,   mis development  ,   data visualization  ,   data hosting and management  ,   collaboration and communication   ,  bi  ,  data warehousing  ,  storage  ,  dashboards  ,  data analytics  ,  information management  ,  data analyst  ,  tableau  ,  data governance 0 - 2 yrs Mumbai https://www.timesjobs.com/job-detail/iron-mountain-jobs-management-trainee-data-analyst-mumbai-in-mumbai-india-iron-mountain-india-pvt-ltd-mumbai-0-to-2-yrs-jobid-KDLZxOWi7TlzpSvf__PLUS__uAgZw==&source=srp
netskope software pvt.ltd data analysis   ,   sql   ,   tableau   ,   looker   ,   python   ,  soft skills  ,  employee recognition 0 - 3 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/intern-cso-data-analyst-spring-2024-summer-2024-netskope-software-pvt-ltd-bengaluru-bangalore-0-to-3-yrs-jobid-Eecf6mKGfBRzpSvf__PLUS__uAgZw==&source=srp
buck global llc data analysis  ,   analytics  ,   database design  ,   business support  ,   data management and reporting   ,  algorithms  ,  data mining  ,  data structures  ,  problem solving  ,  reporting tools 5 - 8 yrs Bengaluru / Bangalore https://www.timesjobs.com/job-detail/de-jobs-ntt-america-solutions-inc-data-analyst-in-bangalore-india-buck-global-llc-bengaluru-bangalore-5-to-8-yrs-jobid-oDw3tg62J41zpSvf__PLUS__uAgZw==&source=srp

In [9]:
df=pd.DataFrame(job,columns=(['Company_Name','Skills','Experience','Location','Link']))

In [20]:
df.head(25)

,Company_Name,Skills,Experience,Location,Link
0,Information Services Group,"data analysis , python , excel , sql ...",2 - 3 yrs,Bengaluru / Bangalore,https://www.timesjobs.com/job-detail/data-anal...
1,Zoxima Solutions Pvt. Ltd.,"reports , Data Analysts , MySQL",3 - 8 yrs,,https://www.timesjobs.com/job-detail/data-anal...
2,RDA Labs,"bi , dashboards , data analyst , impact ...",1 - 3 yrs,Bengaluru / Bangalore,https://www.timesjobs.com/job-detail/data-anal...
3,Best Infosystems Ltd.\r\n,"DATA ANALYST , SAP ABAP , HTML5 and CSS",6 - 10 yr,,https://www.timesjobs.com/job-detail/data-anal...
4,the modern dimension,"oracle , sas , bi , dashboards , data ...",3 - 6 yrs,"Delhi, Delhi/NCR, Bengaluru / Bangalore",https://www.timesjobs.com/job-detail/data-anal...
5,ADROIT LEARNING AND MANPOWER PVT LTD,"data analysis , dashboards , data analyst ...",7 - 10 yr,Ahmedabad,https://www.timesjobs.com/job-detail/data-anal...
6,HyreFox Consultants,"data analytics , business requirements , b...",0 - 3 yrs,Jaipur,https://www.timesjobs.com/job-detail/data-anal...
7,Uscreen,"dashboards , sql , data visualization , ...",3 - 6 yrs,Bengaluru / Bangalore,https://www.timesjobs.com/job-detail/data-anal...
8,cibirix digital media,"advanced analytics , visualization , data ...",2 - 5 yrs,,https://www.timesjobs.com/job-detail/data-anal...
9,Brainvire Infotech,"data analysis , excel proficiency , re...",0 - 1 yrs,Mumbai,https://www.timesjobs.com/job-detail/data-anal...
10,Principal Financial Services Inc.,"visualization , bi , sql , data science ...",0 - 2 yrs,Pune,https://www.timesjobs.com/job-detail/data-anal...
11,Canvas Facilities\r\n,"Data Analysis , data analyst , excel , p...",1 - 6 yrs,,https://www.timesjobs.com/job-detail/data-anal...
12,Canvas Facilities\r\n,"Data Analysis , data analyst , excel , p...",1 - 6 yrs,,https://www.timesjobs.com/job-detail/data-anal...
13,Edifecs,"release planning , business requirements ...",3 - 6 yrs,Mohali,https://www.timesjobs.com/job-detail/data-anal...
14,Edifecs,"release planning , business requirements ...",3 - 6 yrs,Mohali,https://www.timesjobs.com/job-detail/data-anal...
15,Ipseity Group,"reports , vb , data collection , xml , ...",1 - 3 yrs,Bhopal,https://www.timesjobs.com/job-detail/data-anal...
16,advanced risk analytics private limited,"visualizing data , data collection , Flood...",0 - 3 yrs,Pune,https://www.timesjobs.com/job-detail/data-anal...
17,myglamm popxo,"data analysis , excel , sql , pyth...",2 - 4 yrs,Delhi/NCR,https://www.timesjobs.com/job-detail/data-anal...
18,Travel Centric Technology,"information technology , team player , sql",2 - 5 yrs,Bengaluru / Bangalore,https://www.timesjobs.com/job-detail/data-anal...
19,Hexanika,"test data , sql queries , testing , sql",0 - 3 yrs,Pune,https://www.timesjobs.com/job-detail/data-anal...
20,BUSISOL SOURCING INDIA PVT. LTD,"charts , data mining , formulas , relati...",0 - 3 yrs,Mumbai,https://www.timesjobs.com/job-detail/data-anal...
21,zf india pvt ltd,"data analysis , erp systems , ms power...",3 - 6 yrs,Coimbatore,https://www.timesjobs.com/job-detail/data-anal...
22,BUSISOL SOURCING INDIA PVT. LTD,"reports , charts , data mining , formula...",0 - 3 yrs,Delhi,https://www.timesjobs.com/job-detail/data-anal...
23,mobileforce,"website , campaigns , google analytics , ...",0 - 3 yrs,Indonesia,https://www.timesjobs.com/job-detail/data-anal...
24,ANZ GRINDLAYS BANK,"hr data knowledge , business acumen , ad...",8 - 11 yr,Bengaluru / Bangalore,https://www.timesjobs.com/job-detail/data-anal...

In [18]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
245    False
246    False
247    False
248    False
249    False
Length: 250, dtype: bool

In [21]:
#To save the datasets into csv file
df.to_csv('TimesJob.csv')

In [25]:
excel=openpyxl.Workbook()
sheet=excel.active
sheet.title=("TimesJobs")
sheet.append(['Company_Name','Skills','Experience','Location','Link'])

In [27]:
excel.save("TimesJob.xlsx")